import "../styles/rates.less";
import "./rates.html";
import "chart.js";

Template.rates.onCreated(function() {
    this.selectedCryptoCode = new ReactiveVar("BTC");
  });

Template.rates.onRendered(function() {
    let ctx = document.getElementById("priceChart").getContext("2d");
    let chart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: [],
            datasets: [{
                borderColor: '#2374ab',
                backgroundColor: 'rgba(35, 116, 171, 0.3)',
                data: [],
                fill: true,
            }]
        },
        options: {
            maintainAspectRatio: false,
            legend: {
                display: false
            },
            responsive: true,
            tooltips: {
                backgroundColor: 'rgba(255, 255, 255, 0.9)',
                titleFontColor: '#2374ab',
                bodyFontColor: '#2374ab',
                bodyFontSize: 20,
                borderWidth: 2,
                borderColor: '#dddddd',
                mode: 'index',
                yPadding: 10,
                xPadding: 15,
                intersect: false,
                bodyFontStyle: 'bold',
                displayColors: false,
                callbacks: {
                    label: (d) => {
                    return "$"+d.yLabel.toLocaleString()
                    }
                }
            },
            drawBorder: false,
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                    display: true,
                    type: 'time',
                    distribution: 'series',
                    bounds: 'ticks',
                    time: {
                        unit: 'day',
                        tooltipFormat: 'dddd, MMMM Do YYYY'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Price (AUD)'
                    }
                }]
            }
        }
    });

    this.autorun(() => {
        let code = this.selectedCryptoCode.get();
        // Get chart data
        Meteor.call("getChartData", code, (er, res) => {
            console.log(er,res);
            if(er) return sAlert.error("Failed to get chart data.");
            chart.data.labels = res.labels;
            chart.data.datasets[0].data = res.data;
            chart.update();
        });

        $("#info").html(_.find(ratesInfo, function(item) {
            if(item.code == code)
                return item.description;
        }).description);
    });

    window.prerenderReady = true;//Tell pre-render we are now ready
});

Template.rates.helpers({
    selectedCryptoCode() {
        return Template.instance().selectedCryptoCode.get();
    },
});

Template.rates.events({
    "change #cryptos-list "(e, tpl) {
      tpl.selectedCryptoCode.set($("#cryptos-list").val());
    }
});



let ratesInfo = [{
    code: "BTC",
    description: "Bitcoin is the cryptocurrency king. Its current market cap is USD 65 billion. The Bitcoin blockchain provides a decentralized peer-to-peer electronic cash system. Critics could say bitcoin has no intrinsic value, arguing it is a financial asset whose monetary value is entirely derived from people’s perception and, unlike fiat currencies, it has no central bank reserves backing."
},
{
    code: "ETH",
    description: "Ethereum is the second most popular cryptocurrency and the king of Blockchain-As-A-Service. It is a programmable blockchain with a Turing-complete scripting language. Like Bitcoin, it provides a decentralized peer to peer electronic cash system. Unlike Bitcoin, Ethereum allows for the creation of smart contracts (i.e. programming code that auto-executes once certain conditions are fulfilled). And unlike Bitcoin, with Ethereum developers can build and deploy decentralized applications (e.g. an Ethereum-based decentralized Facebook)."
},
{
    code: "LTC",
    description: "Just like bitcoin, litecoin is a crytocurrency that is generated by mining. Litecoin was created in October 2011 by former Google engineer Charles Lee. The motivation behind its creation was to improve upon bitcoin. The key difference for end-users being the 2.5 minute time to generate a block, as opposed to bitcoin's 10 minutes. Charles Lee now works for Coinbase, one of the most popular online bitcoin wallets."
},
{
    code: "NANO",
    description: `RaiBlocks wins. RaiBlocks has zero fees and instant transactions (or as close to instant as can be achieved given the infrastructure limits of ping times and CPU power). Its phenomenal transaction throughput means it’s very likely to be able to be adopted by the whole world without so much as breaking a sweat. It’s infinitely scalable thanks to its block-lattice tech, something that BTC, DASH, ETH and LTC cannot claim with any validity. Of the pure cryptocurrencies (coins like Bitcoin, Bitcoin Cash and Litecoin that operate solely as currencies) it has no equal.`
},
{
    code: "XRP",
    description: `Ripple is the name for both a digital currency (XRP) and an open payment network within which that currency is transferred. It is a distributed, open-source payments system that's still in beta. The goal of the ripple system, according to its website, is to enable people to break free of the "walled gardens" of financial networks – ie, credit cards, banks, PayPal and other institutions that restrict access with fees, charges for currency exchanges and processing delays.`
}
];